services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672 # amqp
      - 5552:5552 # stream
      - 15674:15674 # web_stomp
      - 15670:15670 # web_stomp example: https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_web_stomp_examples
      - 15672:15672 # management ui
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: '[rabbitmq_management, rabbitmq_stream, rabbitmq_web_stomp, rabbitmq_web_stomp_examples].'
    # rabbitmq_stream

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
